apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: wordpress
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAqVOZ9gZXGumxBVh+ht/OIUH4JHV7Sb+4hltuJ7q1PiBxGi2sMj1gZG7ABrKIhNvoL6eFHYLLmY8vit0505vvO8dyVFA8UzLi3efBej6Pypd+Qx2vyMHqG/WyjPEGsxpWDX1moh94lhroRqmRa2kUAYgPngvCqhIXsopD8hJwgJyedPzNAJSg4GbVwH9H9mmGaGuYZwAwxJ9852XWLOt8oaR9PUgoXo8VC1J36qv0x+1Yo7vM/ga0krKpGWQg6tHwVy5hNyxTaMuyyzqIgOmcxyl2w0iz6IXCM2l42x4QJsYcY/JEPAOTzCXA6X1Aw667c4RZ0HcKCi5mULVmFngNR/cZVo5OufSoyDNAhjZmovShZ+dSng1Qw9Hdj+IMk9IHy4zAtIJBoagfMEhw2FERA+YnZUPC6zXqkKfb9W6AxgPAvakBHd2QQvzySYNG6ymCKkiVlcOeyXnQ7TJZzaqk7QIz3ZI67PvRp/MBY+N/S+DMTDm/Ou/vGXXRAwCPxME8/jY6ZHIC2ZQEK1+4Koh9EWaXpKoan9TtADJRgSv0ApNkUPUTW7NexaDH1aOo2JmEvALxzpPVtSveoskS9eOWQWUJ/lkT+FeluINgMUZOIVXSJM+whruwESSe7tknr2XFDFkS3xtE5IvThPPTM+pnZ0Vv7KfQ7xF3EgR8VISVkk7Z55SxEY5MgJIgtA22LDqJVe759uwipXskkuZfGFjPF1qq1B4SoQA9cyBkXkBYJnp8IWX428Ae51JFFRbcGuU0e0xeECUuYJBXIqgjd/wgDYWoVG/ec8scpWYbTRcbQDB+kiNnHi5+rCdCbIKYbc57NrE2xmXT+nUr52oAr5+HjAfLTGNDOgqh2U4eNL8/1xs7SS4PNae14oBRuACyoflMywiCPXQAJQ56uDSUBRaFeK3eNoSPtNEo2ophTJWRE9AYBkDB/b4oy
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: wordpress
    type: Opaque
---
